# Generated by Django 2.0.6 on 2018-06-29 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('balance', models.FloatField()),
                ('lastRequest', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
